name: Release

on:
  push:
    branches: [main]

jobs:
  tag:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          fetch-tags: true
      - name: Calculate and create semver tag
        id: semver
        uses: bitshifted/git-auto-semver@v2
        with:
          create_tag: true
          tag_prefix: v
          initial_version: 0.1.0
